drop table if exists snapshot_token_holding_uni;
CREATE TABLE public.snapshot_token_holding_uni (
                                          address varchar(256) NOT NULL,
                                          "token" varchar(256) NOT NULL,
                                          balance numeric(125, 30) NOT NULL DEFAULT 0,
                                          block_height int8 NOT NULL,
                                          total_transfer_volume numeric(125, 30) NOT NULL DEFAULT 0,
                                          total_transfer_count int8 NOT NULL DEFAULT 0,
                                          status varchar(128) NULL DEFAULT 'PENDING'::character varying,
                                          created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                          updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                          removed bool NULL DEFAULT false,
                                          fail_count int4 NULL DEFAULT 0,
                                          error_code int4 NULL DEFAULT 0,
                                          error_message text NULL,
                                          node_name varchar(512) NULL,
                                          nft_token_id varchar(150) NULL,
                                          in_transfer_volume numeric(125, 30) NULL,
                                          out_transfer_volume numeric(125, 30) NULL,
                                          in_transfer_count int8 NULL,
                                          out_transfer_count int8 NULL,
                                          "event" varchar(10) NULL,
                                          first_updated_block_height int8 NOT NULL DEFAULT 99999999,
                                          transaction_hash varchar(100) NULL,
                                          price_token varchar(150) NULL,
                                          liquidity numeric(125, 30) NULL,
                                          token0 varchar(150) NULL,
                                          token1 varchar(150) NULL,
                                          handle bool NULL DEFAULT true,
                                          "type" varchar(30) NULL
)distributed by (address, token);
truncate table snapshot_token_holding_uni;
vacuum snapshot_token_holding_uni;
    insert into snapshot_token_holding_uni(address ,
                                  "token" ,
                                  balance ,
                                  block_height ,
                                  total_transfer_volume ,
                                  total_transfer_count ,
                                  status ,
                                  created_at ,
                                  updated_at ,
                                  removed,
                                  fail_count ,
                                  error_code ,
                                  error_message ,
                                  node_name ,
                                  nft_token_id ,
                                  in_transfer_volume ,
                                  out_transfer_volume ,
                                  in_transfer_count,
                                  out_transfer_count,
                                  "event" ,
                                  first_updated_block_height  ,
                                  transaction_hash ,
                                  price_token ,
                                  liquidity ,
                                  token0 ,
                                  token1 ,
                                  handle ,
                                  "type")
select address ,
       "token" ,
       balance ,
       block_height ,
       total_transfer_volume ,
       total_transfer_count ,
       status ,
       created_at ,
       updated_at ,
       removed,
       fail_count ,
       error_code ,
       error_message ,
       node_name ,
       nft_token_id ,
       in_transfer_volume ,
       out_transfer_volume ,
       in_transfer_count,
       out_transfer_count,
       "event" ,
       first_updated_block_height  ,
       transaction_hash ,
       price_token ,
       liquidity ,
       token0 ,
       token1 ,
       handle ,
       "type" from token_holding_uni;
insert into tag_result(table_name,batch_date)  SELECT 'snapshot_table' as table_name,to_char(current_date ,'YYYY-MM-DD')  as batch_date;
