apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wired-tag.fullname" . }}
  labels:
    {{- include "wired-tag.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wired-tag.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wired-tag.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: CONFIG_ENVIRONMENT
              value: {{ .Values.config.env | quote }}
            - name: GREENPLUM_DB_HOST
              value: {{ .Values.greenplum.host | quote }}
            - name: GREENPLUM_DB_PORT
              value: {{ .Values.greenplum.port | quote }}
            - name: GREENPLUM_DB_NAME
              value: {{ .Values.greenplum.name | quote }}
            - name: GREENPLUM_DB_USERNAME
              value: {{ .Values.greenplum.username | quote }}
            - name: GREENPLUM_DB_PASSWORD
              value: {{ .Values.greenplum.password | quote }}
            - name: DB_HOST
              value: {{ .Values.ugcDatabase.host | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.ugcDatabase.password | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
