server:
  port: ${PORT:10008}
  base-url: /api

spring:
  application:
    name: relation-ugc-scheduler
  swagger:
    enabled: true
  datasource:
    greenplum:
      url: jdbc:postgresql://${GREENPLUM_DB_HOST:localhost}:${GREENPLUM_DB_PORT:5432}/${GREENPLUM_DB_NAME:postgres}
      username: ${GREENPLUM_DB_USERNAME:readpostgres}
      password: ${GREENPLUM_DB_PASSWORD:hojil@123!}
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      #      druid:
      initial-size: 3
      min-idle: 3
      max-active: 5
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 6000
      max-wait: 5000000
      filters: stat,config

# 日志配置
logging:
  config: classpath:logback-spring-yun.xml
