server:
  port: ${PORT:10008}
  base-url: /api

spring:
  application:
    name: relation-ugc-scheduler
  swagger:
    enabled: true
  datasource:
    primary:
      url: jdbc:postgresql://${DB_HOST:wired-ugc-stag-rds8938bb4.cyaangry9qtf.ap-southeast-1.rds.amazonaws.com}:${DB_PORT:5432}/${DB_NAME:ugc}?currentSchema=public&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&stringtype=unspecified
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:cwhAmb9aFFRDeepJ}
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      #      druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filters: stat,config
#    greenplum:
    url: jdbc:postgresql://${GREENPLUM_DB_HOST:localhost}:${GREENPLUM_DB_PORT:5432}/${GREENPLUM_DB_NAME:eth}
    username: ${GREENPLUM_DB_USERNAME:gpadmin}
    password: ${GREENPLUM_DB_PASSWORD:hojil@123!}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 3000000
      time-between-eviction-runs-millis: 6000000
      min-evictable-idle-time-millis: 30000000
      validation-query: select version()
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,config

# 日志配置
logging:
  config: classpath:logback-spring-yun.xml

config:
  environment: ${CONFIG_ENVIRONMENT:stag}
  tag:
    flag: no-tag
#    flag: tag

